option(LMX_DEPLOYMENT_BUILD "Require installed resources; hide the Windows console" OFF)
if(LMX_DEPLOYMENT_BUILD)
  target_compile_definitions(libremax-architect PRIVATE LMX_INSTALLED_ONLY)
endif()
if(WIN32 AND LMX_DEPLOYMENT_BUILD)
  set_target_properties(libremax-architect PROPERTIES WIN32_EXECUTABLE TRUE)
  target_sources(libremax-architect PRIVATE resources/windows.rc)
  target_include_directories(libremax-architect PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/resources")
endif()
target_compile_definitions(libremax-architect PRIVATE LMX_VERSION="${PROJECT_VERSION}")

install(TARGETS libremax-architect RUNTIME DESTINATION bin)
if(UNIX AND NOT APPLE)
  install(FILES resources/libremax-architect.desktop DESTINATION share/applications)
  install(FILES resources/libremax.svg DESTINATION share/icons/hicolor/scalable/apps)
  install(FILES resources/libremax-project.xml DESTINATION share/mime/packages)
endif()
install(DIRECTORY starter-library/ DESTINATION share/libremax/starter-library)
install(DIRECTORY starter-materials/ DESTINATION share/libremax/starter-materials)
install(DIRECTORY starter-environments/ DESTINATION share/libremax/starter-environments)
install(DIRECTORY starter-models/ DESTINATION share/libremax/starter-models)
install(FILES scripts/cycles_render.py DESTINATION share/libremax/scripts)
install(FILES resources/style.qss DESTINATION share/libremax/resources)
install(DIRECTORY examples/ DESTINATION share/libremax/examples)
install(FILES LICENSE README.md docs/THIRD_PARTY.md DESTINATION share/doc/libremax-architect)
set(CPACK_PACKAGE_NAME libremax-architect)
if(UNIX AND NOT APPLE)
  set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
endif()
set(CPACK_PACKAGE_CONTACT "LibreMax contributors")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Editor desktop de arquitetura de interiores — previa de desenvolvimento")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_SECTION graphics)
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libqt6sql6-sqlite, libxcb-cursor0, shared-mime-info, desktop-file-utils, xwayland")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE amd64)
set(CPACK_PACKAGE_FILE_NAME "LibreMax-Architect-${PROJECT_VERSION}-Linux-Ubuntu24.04-amd64")
set(CPACK_GENERATOR "DEB;TGZ")
include(CPack)
